## Build stage

FROM golang:1.21 AS build-stage

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /build ./cmd/api/main.go



## Release stage

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /build /build

EXPOSE 3001

USER nonroot:nonroot

# Run
CMD [ "/build" ]