version: '3.3'

services:
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/go/src/app
    env_file:
      - .env

  # mysql: 
  #   image: mysql:8
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: accounts
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
