name: Deploy Accounts

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Pull files
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_SECRET }}
                ARGS: "-rltgoDzvO --delete"
                SOURCE: "."
                REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
                REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
                TARGET: ${{ vars.SERVER_WORK_DIR }}
                EXCLUDE: "/.github/"
                SCRIPT_AFTER: |
                    cd ${{ vars.SERVER_WORK_DIR }}
                    echo "DB_NAME=\"${{vars.DB_NAME}}\"" > .env
                    echo "DB_HOST=\"${{secrets.DB_HOST}}\"" >> .env
                    echo "DB_USER=\"${{secrets.DB_USER}}\"" >> .env
                    echo "DB_PASS=\"${{secrets.DB_PASS}}\"" >> .env
                    echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
                    docker-compose down
                    docker-compose start
  